### ISSUE TITLE
[Settings] #1 - 깃 초기 세팅

### ISSUE THREAD

**Issue by cantabilano** [Weather-777/weather777#1]
- [x] 폴더링 : Network, WeatherList, Map, Main, Support
- [x] add Package dependencies : Snapkit, Then
- [x] gitignore
- [x] issue && pull request template

토의 : dev branch 사용여부

**Comment by RACHEL056** [comment]
Support 폴더의 용도는 무엇일까요? 어떤 파일들이 들어가게 될까요?

**Comment by cantabilano** [comment]
디자인패턴에 포함하지 않은 내용(AppDelagate, SceneDelgate, Assets)들이 들어가게 됩니다.
